[build]
  command = "npm run build"
  publish = "public/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-no-more-404"

# Redirects from subfolders to subdomains
[[redirects]]
  from = "/learning-es6"
  to = "https://learning-es6.benmvp.com/"
[[redirects]]
  from = "/you-dont-need-js-for-that"
  to = "https://you-dont-need-js-for-that.benmvp.com/"

# Post redirects from /* to /blog/*
[[redirects]]
  from = "/new-blog/"
  to = "/blog/new-blog/"
[[redirects]]
  from = "/learning-es6-history-of-ecmascript/"
  to = "/blog/learning-es6-history-of-ecmascript/"
[[redirects]]
  from = "/learning-es6-goals-features-ecmascript-6/"
  to = "/blog/learning-es6-goals-features-ecmascript-6/"
[[redirects]]
  from = "/learning-es6-using-es6-right-now/"
  to = "/blog/learning-es6-using-es6-right-now/"
[[redirects]]
  from = "/20-reasons-to-drop-ie8-like-its-hot/"
  to = "/blog/20-reasons-to-drop-ie8-like-its-hot/"
[[redirects]]
  from = "/learning-es6-arrow-functions/"
  to = "/blog/learning-es6-arrow-functions/"
[[redirects]]
  from = "/learning-es6-block-level-scoping-let-const/"
  to = "/blog/learning-es6-block-level-scoping-let-const/"
[[redirects]]
  from = "/learning-es6-destructuring/"
  to = "/blog/learning-es6-destructuring/"
[[redirects]]
  from = "/speaking-at-little-rock-tech-fest-2015/"
  to = "/blog/speaking-at-little-rock-tech-fest-2015/"
[[redirects]]
  from = "/learning-es6-parameter-handling/"
  to = "/blog/learning-es6-parameter-handling/"
[[redirects]]
  from = "/learning-es6-enhanced-object-literals/"
  to = "/blog/learning-es6-enhanced-object-literals/"
[[redirects]]
  from = "/learning-es6-template-literals-tagged-templates/"
  to = "/blog/learning-es6-template-literals-tagged-templates/"
[[redirects]]
  from = "/learning-es6-promises/"
  to = "/blog/learning-es6-promises/"
[[redirects]]
  from = "/little-rock-tech-fest-2015/"
  to = "/blog/little-rock-tech-fest-2015/"
[[redirects]]
  from = "/nodevember-2015/"
  to = "/blog/nodevember-2015/"
[[redirects]]
  from = "/learning-es6-for-of-loop/"
  to = "/blog/learning-es6-for-of-loop/"
[[redirects]]
  from = "/learning-es6-classes/"
  to = "/blog/learning-es6-classes/"
[[redirects]]
  from = "/learning-es6-new-collections/"
  to = "/blog/learning-es6-new-collections/"
[[redirects]]
  from = "/learning-es6-iterators-iterables/"
  to = "/blog/learning-es6-iterators-iterables/"
[[redirects]]
  from = "/learning-es6-generators-as-iterators/"
  to = "/blog/learning-es6-generators-as-iterators/"
[[redirects]]
  from = "/nationjs-nodeday-2016/"
  to = "/blog/nationjs-nodeday-2016/"
[[redirects]]
  from = "/ndc-oslo-2016/"
  to = "/blog/ndc-oslo-2016/"
[[redirects]]
  from = "/front-porch-austin-2016/"
  to = "/blog/front-porch-austin-2016/"
[[redirects]]
  from = "/nodesummit-2016/"
  to = "/blog/nodesummit-2016/"
[[redirects]]
  from = "/learning-es6-12-tricks-for-es6-fun/"
  to = "/blog/learning-es6-12-tricks-for-es6-fun/"
[[redirects]]
  from = "/new-gatsby-blog/"
  to = "/blog/new-gatsby-blog/"
[[redirects]]
  from = "/microsoft-mvp/"
  to = "/blog/microsoft-mvp/"

# Slides redirects from /slides to slides.benmvp.com

[[redirects]]
  from = "/slides/confoo2016-es6.html"
  to = "https://slides.benmvp.com/2016/confoo/es6"

[[redirects]]
  from = "/slides/confoo2016-no-js.html"
  to = "https://slides.benmvp.com/2016/confoo/no-js"

[[redirects]]
  from = "/slides/devweek2016-es6.html"
  to = "https://slides.benmvp.com/2016/devweek/es6"

[[redirects]]
  from = "/slides/evbeng-js-coding-style-results.html"
  to = "https://slides.benmvp.com/2016/evbeng/eslint"

[[redirects]]
  from = "/slides/evbeng-js-coding-style.html"
  to = "https://slides.benmvp.com/2015/evbeng/eslint"

[[redirects]]
  from = "/slides/fossetcon2015-no-js.html"
  to = "https://slides.benmvp.com/2015/fossetcon/no-js"

[[redirects]]
  from = "/slides/nationjs2016-es6.html"
  to = "https://slides.benmvp.com/2016/nationjs/es6"

[[redirects]]
  from = "/slides/nodevember2015-es6.html"
  to = "https://slides.benmvp.com/2015/nodevember/es6"

[[redirects]]
  from = "/slides/prairiedevcon2016-es6.html"
  to = "https://slides.benmvp.com/2016/prdc/es6"

[[redirects]]
  from = "/slides/prairiedevcon2016-no-js.html"
  to = "https://slides.benmvp.com/2016/prdc/no-js"

[[redirects]]
  from = "/slides/sacjs2015-no-js.html"
  to = "https://slides.benmvp.com/2015/sacjs/no-js"

[[redirects]]
  from = "/slides/2015/nodevember/es6.html"
  to = "https://slides.benmvp.com/2015/nodevember/es6"

[[redirects]]
  from = "/slides/2015/evbeng/eslint.html"
  to = "https://slides.benmvp.com/2015/evbeng/eslint"

[[redirects]]
  from = "/slides/2015/sacjs/no-js.html"
  to = "https://slides.benmvp.com/2015/sacjs/no-js"

[[redirects]]
  from = "/slides/2015/fossetcon/no-js.html"
  to = "https://slides.benmvp.com/2015/fossetcon/no-js"

[[redirects]]
  from = "/slides/2017/mwdcon/react-esnext.html"
  to = "https://slides.benmvp.com/2017/mwdcon/react-esnext"

[[redirects]]
  from = "/slides/2017/reactconf/react-esnext.html"
  to = "https://slides.benmvp.com/2017/reactconf/react-esnext"

[[redirects]]
  from = "/slides/2017/nodevember/why-react.html"
  to = "https://slides.benmvp.com/2017/nodevember/why-react"

[[redirects]]
  from = "/slides/2017/jazzcon/react-exposed.html"
  to = "https://slides.benmvp.com/2017/jazzcon/react-exposed"

[[redirects]]
  from = "/slides/2017/jazzcon/nav-react.html"
  to = "https://slides.benmvp.com/2017/jazzcon/nav-react"

[[redirects]]
  from = "/slides/2017/jazzcon/react-esnext.html"
  to = "https://slides.benmvp.com/2017/jazzcon/react-esnext"

[[redirects]]
  from = "/slides/2017/devweek/nav-react.html"
  to = "https://slides.benmvp.com/2017/devweek/nav-react"

[[redirects]]
  from = "/slides/2017/evbeng/fiber.html"
  to = "https://slides.benmvp.com/2017/evbeng/fiber"

[[redirects]]
  from = "/slides/2017/devoxxus/nav-react.html"
  to = "https://slides.benmvp.com/2017/devoxxus/nav-react"

[[redirects]]
  from = "/slides/2017/buzzjs/react-esnext.html"
  to = "https://slides.benmvp.com/2017/buzzjs/react-esnext"

[[redirects]]
  from = "/slides/2017/fluent/flexbox.html"
  to = "https://slides.benmvp.com/2017/fluent/flexbox"

[[redirects]]
  from = "/slides/2017/reactboston/fiber.html"
  to = "https://slides.benmvp.com/2017/reactboston/fiber"

[[redirects]]
  from = "/slides/2017/hackbright/sweet-es6.html"
  to = "https://slides.benmvp.com/2017/hackbright/sweet-es6"

[[redirects]]
  from = "/slides/2017/hackbright/es6.html"
  to = "https://slides.benmvp.com/2017/hackbright/es6"

[[redirects]]
  from = "/slides/2017/strangeloop/react-workshop.html"
  to = "https://slides.benmvp.com/2017/strangeloop/react-workshop"

[[redirects]]
  from = "/slides/2017/render/iso-react.html"
  to = "https://slides.benmvp.com/2017/render/iso-react"

[[redirects]]
  from = "/slides/2017/oscon/react-properly.html"
  to = "https://slides.benmvp.com/2017/oscon/react-properly"

[[redirects]]
  from = "/slides/2017/telegraph/why-react.html"
  to = "https://slides.benmvp.com/2017/telegraph/why-react"

[[redirects]]
  from = "/slides/2017/revconf/esnext.html"
  to = "https://slides.benmvp.com/2017/revconf/esnext"

[[redirects]]
  from = "/slides/2017/revconf/nav-react.html"
  to = "https://slides.benmvp.com/2017/revconf/nav-react"

[[redirects]]
  from = "/slides/2017/fogcityruby/es6.html"
  to = "https://slides.benmvp.com/2017/fogcityruby/es6"

[[redirects]]
  from = "/slides/2017/forwardjs/react-exposed.html"
  to = "https://slides.benmvp.com/2017/forwardjs/react-exposed"

[[redirects]]
  from = "/slides/2017/chainreact/react-native-esnext.html"
  to = "https://slides.benmvp.com/2017/chainreact/react-native-esnext"

[[redirects]]
  from = "/slides/2017/rwreact/fiber.html"
  to = "https://slides.benmvp.com/2017/rwreact/fiber"

[[redirects]]
  from = "/slides/2017/reactsf/react-exposed.html"
  to = "https://slides.benmvp.com/2017/reactsf/react-exposed"

[[redirects]]
  from = "/slides/2017/sabio/esnext.html"
  to = "https://slides.benmvp.com/2017/sabio/esnext"

[[redirects]]
  from = "/slides/2017/reactathon/esnext.html"
  to = "https://slides.benmvp.com/2017/reactathon/esnext"

[[redirects]]
  from = "/slides/2017/nodesummit/iso-react.html"
  to = "https://slides.benmvp.com/2017/nodesummit/iso-react"

[[redirects]]
  from = "/slides/2017/fstoco/iso-react.html"
  to = "https://slides.benmvp.com/2017/fstoco/iso-react"

[[redirects]]
  from = "/slides/2017/reactrally/fiber.html"
  to = "https://slides.benmvp.com/2017/reactrally/fiber"

[[redirects]]
  from = "/slides/2017/modernweb/nav-react.html"
  to = "https://slides.benmvp.com/2017/modernweb/nav-react"

[[redirects]]
  from = "/slides/2019/svcc/react-eco.html"
  to = "https://slides.benmvp.com/2019/svcc/react-eco"

[[redirects]]
  from = "/slides/2019/cssconfeu/webdev.html"
  to = "https://slides.benmvp.com/2019/cssconfeu/webdev"

[[redirects]]
  from = "/slides/2019/nationjs/react-eco.html"
  to = "https://slides.benmvp.com/2019/nationjs/react-eco"

[[redirects]]
  from = "/slides/2019/reactathon/react-eco.html"
  to = "https://slides.benmvp.com/2019/reactathon/react-eco"

[[redirects]]
  from = "/slides/2019/ato/react-eco.html"
  to = "https://slides.benmvp.com/2019/ato/react-eco"

[[redirects]]
  from = "/slides/2019/webu/webdev.html"
  to = "https://slides.benmvp.com/2019/webu/webdev"

[[redirects]]
  from = "/slides/2020/flashback/webdev.html"
  to = "https://slides.benmvp.com/2020/flashback/webdev"

[[redirects]]
  from = "/slides/2020/jsconfhi/perfect-lib.html"
  to = "https://slides.benmvp.com/2020/jsconfhi/perfect-lib"

[[redirects]]
  from = "/slides/2018/sabiola/react-workshop.html"
  to = "https://slides.benmvp.com/2018/sabiola/react-workshop"

[[redirects]]
  from = "/slides/2018/reactalicante/react-workshop.html"
  to = "https://slides.benmvp.com/2018/reactalicante/react-workshop"

[[redirects]]
  from = "/slides/2018/reactalicante/react-perf.html"
  to = "https://slides.benmvp.com/2018/reactalicante/react-perf"

[[redirects]]
  from = "/slides/2018/nejs/webdev.html"
  to = "https://slides.benmvp.com/2018/nejs/webdev"

[[redirects]]
  from = "/slides/2018/evbeng/why-react.html"
  to = "https://slides.benmvp.com/2018/evbeng/why-react"

[[redirects]]
  from = "/slides/2018/frameworksummit/nav-react.html"
  to = "https://slides.benmvp.com/2018/frameworksummit/nav-react"

[[redirects]]
  from = "/slides/2018/mctech/react-workshop.html"
  to = "https://slides.benmvp.com/2018/mctech/react-workshop"

[[redirects]]
  from = "/slides/2018/ndcsydney/nav-react.html"
  to = "https://slides.benmvp.com/2018/ndcsydney/nav-react"

[[redirects]]
  from = "/slides/2018/reactathon/react-workshop.html"
  to = "https://slides.benmvp.com/2018/reactathon/react-workshop"

[[redirects]]
  from = "/slides/2018/reactathon/why-react.html"
  to = "https://slides.benmvp.com/2018/reactathon/why-react"

[[redirects]]
  from = "/slides/2018/nodesummit/esnext.html"
  to = "https://slides.benmvp.com/2018/nodesummit/esnext"

[[redirects]]
  from = "/slides/2018/reactnext/react-eco.html"
  to = "https://slides.benmvp.com/2018/reactnext/react-eco"

[[redirects]]
  from = "/slides/2016/devweek/es6.html"
  to = "https://slides.benmvp.com/2016/devweek/es6"

[[redirects]]
  from = "/slides/2016/evbeng/react-workshop.html"
  to = "https://slides.benmvp.com/2016/evbeng/react-workshop"

[[redirects]]
  from = "/slides/2016/evbeng/eslint.html"
  to = "https://slides.benmvp.com/2016/evbeng/eslint"

[[redirects]]
  from = "/slides/2016/thunderplains/react-esnext.html"
  to = "https://slides.benmvp.com/2016/thunderplains/react-esnext"

[[redirects]]
  from = "/slides/2016/ndcoslo/no-js.html"
  to = "https://slides.benmvp.com/2016/ndcoslo/no-js"

[[redirects]]
  from = "/slides/2016/rwreact/iso-react.html"
  to = "https://slides.benmvp.com/2016/rwreact/iso-react"

[[redirects]]
  from = "/slides/2016/reactsf/react-esnext.html"
  to = "https://slides.benmvp.com/2016/reactsf/react-esnext"

[[redirects]]
  from = "/slides/2016/nationjs/es6.html"
  to = "https://slides.benmvp.com/2016/nationjs/es6"

[[redirects]]
  from = "/slides/2016/syntaxcon/no-js.html"
  to = "https://slides.benmvp.com/2016/syntaxcon/no-js"

[[redirects]]
  from = "/slides/2016/syntaxcon/es6.html"
  to = "https://slides.benmvp.com/2016/syntaxcon/es6"

[[redirects]]
  from = "/slides/2016/confoo/no-js.html"
  to = "https://slides.benmvp.com/2016/confoo/no-js"

[[redirects]]
  from = "/slides/2016/confoo/sweet-es6.html"
  to = "https://slides.benmvp.com/2016/confoo/sweet-es6"

[[redirects]]
  from = "/slides/2016/confoo/es6.html"
  to = "https://slides.benmvp.com/2016/confoo/es6"

[[redirects]]
  from = "/slides/2016/confoo/flexbox.html"
  to = "https://slides.benmvp.com/2016/confoo/flexbox"

[[redirects]]
  from = "/slides/2016/connect/iso-react.html"
  to = "https://slides.benmvp.com/2016/connect/iso-react"

[[redirects]]
  from = "/slides/2016/connect/nav-react.html"
  to = "https://slides.benmvp.com/2016/connect/nav-react"

[[redirects]]
  from = "/slides/2016/frontporch/react-esnext.html"
  to = "https://slides.benmvp.com/2016/frontporch/react-esnext"

[[redirects]]
  from = "/slides/2016/prdc/no-js.html"
  to = "https://slides.benmvp.com/2016/prdc/no-js"

[[redirects]]
  from = "/slides/2016/prdc/es6.html"
  to = "https://slides.benmvp.com/2016/prdc/es6"

