name: CI

on: [push, pull_request]

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        env:
          CI: true
