name: CI

on: push

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint
        env:
          CI: true

      - name: Run type-checking
        run: pnpm run type-check
        env:
          CI: true
